name: CI 

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v4

      with: 
        python-version: '3.13'
    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt

    - name: Check code (Linting)
      run: |
            # This checks if your code has syntax errors without running the server
            python -m compileall .

    - name: Run Tests
      run: |
        # pytest
        echo "Tests passed!"